#!/usr/bin/env python3
"""Writes COVERAGE.md: every game MAME's driver knows, what assets exist
for it locally, whether it is built, and what blocks the rest.

Run after any batch or asset change:
  python3 tools/gw/extract_inputs.py sm510/ref/hh_sm510.cpp tools/gw/inputs.json
  python3 tools/gw/coverage.py
"""
import glob, json, os, re, sys, datetime

CORES = {'sm5a', 'sm510', 'sm511', 'sm512'}   # verified Lua cores


def title_of(e):
    t = e['title'].replace('Game & Watch: ', '')
    maker = e['maker']
    m = re.match(r'bootleg \((.+)\)$', maker)
    if m:
        maker = m.group(1)
    v = re.match(r'^(.*?)\s*\((.+)\)$', t)
    if v and v.group(2) == maker:
        n = '%s (%s)' % (v.group(1), maker)
    elif v:
        n = '%s (%s, %s)' % (v.group(1), maker, v.group(2))
    else:
        n = '%s (%s)' % (t, maker)
    return n.replace('/', '-').replace(':', ' -')


def main():
    root = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
    os.chdir(root)
    d = json.load(open('tools/gw/inputs.json'))
    built = {os.path.basename(f)[:-4] for f in glob.glob('games-out/*.mgw')}

    rows = []
    for r, e in sorted(d.items()):
        rows.append({
            'rom': r, 'cpu': e['cpu'] or '?', 'title': title_of(e),
            'have_rom': os.path.exists('roms/mame/%s.zip' % r),
            'have_art': os.path.exists('roms/artwork/%s.zip' % r),
            'built': title_of(e) in built,
        })

    def sec(pred):
        return [x for x in rows if pred(x)]

    playable = sec(lambda x: x['built'])
    no_art = sec(lambda x: x['have_rom'] and not x['have_art'] and not x['built'])
    drawn = sec(lambda x: x['built'] and not x['have_art'])
    no_rom = sec(lambda x: not x['have_rom'] and x['have_art'])
    neither = sec(lambda x: not x['have_rom'] and not x['have_art'])
    no_core = sec(lambda x: x['have_rom'] and x['cpu'] not in CORES)
    rom_art_unbuilt = sec(lambda x: x['have_rom'] and x['have_art']
                          and not x['built'] and x['cpu'] in CORES)

    out = []
    w = out.append
    w('# Coverage')
    w('')
    w('Generated by `tools/gw/coverage.py` on %s. Do not edit by hand;'
      % datetime.date.today().isoformat())
    w('regenerate after any batch or asset change.')
    w('')
    w('| | count |')
    w('|---|---|')
    w('| games in the MAME driver | %d |' % len(rows))
    w('| built and installed | %d |' % len(playable))
    w('| of which drawn-panel (no artwork pack yet) | %d |' % len(drawn))
    w('| blocked: no ROM dump locally | %d |' % (len(no_rom) + len(neither)))
    w('| blocked: chip not ported (%s) | %d |'
      % (', '.join(sorted({x['cpu'] for x in no_core})) or '-', len(no_core)))
    w('| have ROM, awaiting artwork (playable via drawn panel) | %d |' % len(no_art))
    w('| have ROM + artwork, not yet built | %d |' % len(rom_art_unbuilt))
    w('')

    def table(title, items, note=''):
        if not items:
            return
        w('## %s (%d)' % (title, len(items)))
        if note:
            w('')
            w(note)
        w('')
        w('| romset | chip | title |')
        w('|---|---|---|')
        for x in items:
            w('| %s | %s | %s |' % (x['rom'], x['cpu'], x['title']))
        w('')

    table('Have ROM, no artwork pack', no_art,
          'Buildable today with the generated drawn panel; each rebuilds '
          'into its authentic shell in seconds once a pack exists.')
    table('Built with the drawn panel, awaiting artwork', drawn,
          'Playable now; watching for artwork packs to upgrade them.')
    table('Artwork exists, no ROM dump locally', no_rom,
          'Several were added to MAME after 0.260; a newer romset '
          'collection may cover them.')
    table('Neither ROM nor artwork locally', neither)
    table('ROM present, chip not ported yet', no_core,
          'Next core ports, same recipe as the three verified ones.')
    table('Assets complete but unbuilt', rom_art_unbuilt,
          'Should be empty; anything here means the batch skipped it.')

    open('COVERAGE.md', 'w').write('\n'.join(out) + '\n')
    print('wrote COVERAGE.md: %d driver games, %d built, %d awaiting art, '
          '%d awaiting ROM, %d awaiting core'
          % (len(rows), len(playable), len(no_art),
             len(no_rom) + len(neither), len(no_core)))


if __name__ == '__main__':
    sys.exit(main())
